env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:svelte/prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
ignorePatterns:
  - "scripts/setupTypeScript.js"
  - "rollup.config.js"
