name: Format

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: ">=21.5.0"
      - run: npm ci # or yarn install

      - name: Prettify code
        run: |
          npx prettier --check .
